# Generated by Django 2.1.1 on 2018-09-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_marketschedule_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='place',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='short_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='url_image',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
