# Generated by Django 2.1.1 on 2018-12-23 18:08

from django.db import migrations, models
import django.db.models.deletion
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_markettype_url_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 'Product'), (2, 'Price'), (3, 'Access')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Market')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=markets.models.get_market_file_path)),
                ('url_image', models.URLField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Market')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.MarketType')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 'Product'), (2, 'Price'), (3, 'Access')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Merchant')),
            ],
        ),
    ]
