# Generated by Django 2.1.1 on 2018-12-23 19:08

from django.db import migrations, models
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_marketrate_merchant_merchantrate_merchantschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketrate',
            name='type',
            field=models.IntegerField(choices=[(1, 'Product'), (2, 'Price'), (3, 'Access')], default=1),
        ),
        migrations.AddField(
            model_name='merchantrate',
            name='type',
            field=models.IntegerField(choices=[(1, 'Product'), (2, 'Price'), (3, 'Access')], default=1),
        ),
        migrations.AlterField(
            model_name='marketrate',
            name='rate',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=markets.models.get_merchant_file_path),
        ),
        migrations.AlterField(
            model_name='merchantrate',
            name='rate',
            field=models.FloatField(default='0.00'),
        ),
    ]
